# Generated by Django 4.0.4 on 2022-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.IntegerField()),
                ('maritalStatus', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('availableVacations', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
