# Generated by Django 4.0.4 on 2022-05-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_systems_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('employee_id', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
