# Generated by Django 4.0.4 on 2022-05-25 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_systems_api', '0002_vacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='vacation',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='hr_systems_api.employee'),
        ),
    ]
