# Generated by Django 4.0.4 on 2022-05-25 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_systems_api', '0003_remove_vacation_employee_id_vacation_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_systems_api.employee'),
        ),
    ]
