# Generated by Django 4.0.4 on 2022-05-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_systems_api', '0004_alter_vacation_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='maritalStatus',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.TextField(),
        ),
    ]
